name       : kirigami2
version    : 5.67.1
release    : 34
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.67/kirigami2-5.67.1.tar.xz : 0311ba00b213a26acddd9fe4ce0642ed2500a076429ea5fe4424fdf634f12e68
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : desktop.kde
optimize   : lto
summary    : QtQuick components for mobile and desktop UI development.
description: |
    Kirigami is a set of QtQuick components for the creation of applications that look and feel great on mobile as well as desktop devices and follow the Kirigami Human Interface Guidelines.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5QuickControls2)
    - extra-cmake-modules
    - qt5-graphicaleffects
rundeps    :
    - qt5-graphicaleffects
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
