name       : kirigami2
version    : 5.52.0
release    : 17
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.52/kirigami2-5.52.0.tar.xz : 375ec103d56a71ee3a5f43de1cfb4720fc33c125b2b2de545f9e563851c38c24
license    : LGPL-2.0-or-later
component  : desktop.kde
optimize   : lto
summary    : QtQuick components for mobile and desktop UI development.
description: |
    Kirigami is a set of QtQuick components for the creation of applications that look and feel great on mobile as well as desktop devices and follow the Kirigami Human Interface Guidelines.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5QuickControls2)
    - extra-cmake-modules
rundeps    :
    - qt5-graphicaleffects
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
