name       : kirigami2
version    : 5.53.0
release    : 18
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.53/kirigami2-5.53.0.tar.xz : 31fe9116af88bb2e4016087b29b01c9ab1bc651b1ec4cf7cbb6e70fea93e792b
license    : LGPL-2.0-or-later
component  : desktop.kde
optimize   : lto
summary    : QtQuick components for mobile and desktop UI development.
description: |
    Kirigami is a set of QtQuick components for the creation of applications that look and feel great on mobile as well as desktop devices and follow the Kirigami Human Interface Guidelines.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5QuickControls2)
    - extra-cmake-modules
rundeps    :
    - qt5-graphicaleffects
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
