name       : kirigami2
version    : 5.101.0
release    : 64
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.101/kirigami2-5.101.0.tar.xz : 7608eeb528ee863441270cb5896628f8f592dcf09ad00d5bd76d5f7dc1578fbd
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : desktop.kde
summary    : QtQuick components for mobile and desktop UI development.
description: |
    Kirigami is a set of QtQuick components for the creation of applications that look and feel great on mobile as well as desktop devices and follow the Kirigami Human Interface Guidelines.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
    - qt5-graphicaleffects
rundeps    :
    - qt5-graphicaleffects
    - qt5-quickcontrols2
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
