name       : kirigami2
version    : 2.2.0
release    : 1
source     :
    - https://download.kde.org/stable/kirigami/kirigami2-2.2.0.tar.xz : b8e0b5088c39740dd002d5bf8046ea219cb63f7d9e19083202f7ba05cc3a4c05
license    : LGPL-2.0
component  : desktop.library
summary    : QtQuick components for mobile and desktop UI development.
description: |
    Kirigami is a set of QtQuick components for the creation of applications that look and feel great on mobile as well as desktop devices and follow the Kirigami Human Interface Guidelines.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5QuickControls2)
    - extra-cmake-modules
setup      : |
    mkdir ./build
    cd ./build
    %cmake ..
build      : |
    %make -C build
install    : |
    %make_install -C build
