name       : kirigami2
version    : 5.77.0
release    : 43
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.77/kirigami2-5.77.0.tar.xz : aa4941f63e903ffdb029621739595c67acf02f16a2bca3657693c1fd5e503d96
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : desktop.kde
optimize   : lto
summary    : QtQuick components for mobile and desktop UI development.
description: |
    Kirigami is a set of QtQuick components for the creation of applications that look and feel great on mobile as well as desktop devices and follow the Kirigami Human Interface Guidelines.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5QuickControls2)
    - extra-cmake-modules
    - qt5-graphicaleffects
rundeps    :
    - qt5-graphicaleffects
    - qt5-quickcontrols2
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
