name       : kirigami2
version    : 5.83.0
release    : 50
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.83/kirigami2-5.83.0.tar.xz : 5b8e667e49e349c0ea6e402f906ab542bae3e4cbf37a8a3d5a7848421eb6fc32
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : desktop.kde
summary    : QtQuick components for mobile and desktop UI development.
description: |
    Kirigami is a set of QtQuick components for the creation of applications that look and feel great on mobile as well as desktop devices and follow the Kirigami Human Interface Guidelines.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
    - qt5-graphicaleffects
rundeps    :
    - qt5-graphicaleffects
    - qt5-quickcontrols2
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
