name       : kirigami2
version    : 5.58.0
release    : 24
source     :
    - https://download.kde.org/stable/frameworks/5.58/kirigami2-5.58.0.tar.xz : ad54e15c03807181313e29013057cf89cb70113f74a26ab7aec6420cdc18d9b3
license    : LGPL-2.0-or-later
component  : desktop.kde
optimize   : lto
summary    : QtQuick components for mobile and desktop UI development.
description: |
    Kirigami is a set of QtQuick components for the creation of applications that look and feel great on mobile as well as desktop devices and follow the Kirigami Human Interface Guidelines.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5QuickControls2)
    - extra-cmake-modules
    - qt5-graphicaleffects
rundeps    :
    - qt5-graphicaleffects
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
