name       : kirigami2
version    : 5.42.0
release    : 7
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.42/kirigami2-5.42.0.tar.xz : 1b5bbce792db12e19aaa41095c8b9d7f662a98d3f1358ae05b29835bd5b1f885
license    : LGPL-2.0
component  : desktop.kde
optimize   : lto
summary    : QtQuick components for mobile and desktop UI development.
description: |
    Kirigami is a set of QtQuick components for the creation of applications that look and feel great on mobile as well as desktop devices and follow the Kirigami Human Interface Guidelines.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5QuickControls2)
    - extra-cmake-modules
    - plasma-framework-devel
rundeps    :
    - qt5-graphicaleffects
setup      : |
    mkdir build && cd build
    %cmake ..
build      : |
    %make -C build
install    : |
    %make_install -C build
    cd $installdir; qml_cache
